from . import ir_http
from . import payment_transaction
from . import pos_category
from . import pos_config
from . import pos_order
from . import pos_printer
from . import pos_session
from . import product_product
from . import res_partner
from . import res_users
